name: calendar
description: Flutter Calendar Component
version: 0.0.1
author: Michael Perrotte
homepage:

flutter:

dependencies:
  flutter:
    sdk: flutter
  flutter_flux: '>=4.0.1'
  http: '>=0.11.3+14'


dev_dependencies:
  test: ^0.12.0
